In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [35]:
data=pd.read_csv("Logistic_Regression_Binary_Classsification_Churn_Data.csv")
data.head(2)

customerID  tenure PhoneService        Contract PaperlessBilling  \
0  7590-VHVEG       1           No  Month-to-month              Yes   
1  5575-GNVDE      34          Yes        One year               No   

      PaymentMethod  MonthlyCharges TotalCharges Churn  
0  Electronic check           29.85        29.85    No  
1      Mailed check           56.95       1889.5    No

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
customerID          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
dtypes: float64(1), int64(1), object(7)
memory usage: 495.3+ KB


In [37]:
data.keys()

Index(['customerID', 'tenure', 'PhoneService', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [38]:
churn=pd.get_dummies(data["Churn"],drop_first=True)
churn.head(2)

Yes
0    0
1    0

In [39]:
phone_service=pd.get_dummies(data["PhoneService"],drop_first=True)
phone_service.head(2)


Yes
0    0
1    1

In [40]:
paperless_billing=pd.get_dummies(data["PaperlessBilling"],drop_first=True)
paperless_billing.head(2)

Yes
0    1
1    0

In [69]:
cont=pd.get_dummies(data["Contract"],drop_first=True)
cont.head(2)

One year  Two year
0         0         0
1         1         0

In [71]:
method=pd.get_dummies(data["PaymentMethod"],drop_first=True)
method.head(2)


Credit card (automatic)  Electronic check  Mailed check
0                        0                 1             0
1                        0                 0             1

In [93]:
df=pd.concat([data.MonthlyCharges,data.TotalCharges,data.tenure,paperless_billing,phone_service,cont,method,churn],axis=1)
df

MonthlyCharges TotalCharges  tenure  Yes  Yes  One year  Two year  \
0              29.85        29.85       1    1    0         0         0   
1              56.95       1889.5      34    0    1         1         0   
2              53.85       108.15       2    1    1         0         0   
3              42.30      1840.75      45    0    0         1         0   
4              70.70       151.65       2    1    1         0         0   
5              99.65        820.5       8    1    1         0         0   
6              89.10       1949.4      22    1    1         0         0   
7              29.75        301.9      10    0    0         0         0   
8             104.80      3046.05      28    1    1         0         0   
9              56.15      3487.95      62    0    1         1         0   
10             49.95       587.45      13    1    1         0         0   
11             18.95        326.8      16    0    1         0         1   
12            100.35       5681.1      58    0    1         1         0   
13            103.70       5036.3      49    1    1         0         0   
14            105.50      2686.05      25    1    1         0         0   
15            113.25      7895.15      69    0    1         0         1   
16             20.65      1022.95      52    0    1         1         0   
17            106.70      7382.25      71    0    1         0         1   
18             55.20       528.35      10    0    1         0         0   
19             90.05       1862.9      21    1    1         0         0   
20             39.65        39.65       1    1    0         0         0   
21             19.80       202.25      12    0    1         1         0   
22             20.15        20.15       1    0    1         0         0   
23             59.90       3505.1      58    1    1         0         1   
24             59.60       2970.3      49    0    1         0         0   
25             55.30       1530.6      30    1    1         0         0   
26             99.35      4749.15      47    1    1         0         0   
27             30.20         30.2       1    0    0         0         0   
28             90.25      6369.45      72    1    1         0         1   
29             64.70       1093.1      17    1    1         0         0   
...              ...          ...     ...  ...  ...       ...       ...   
7013           93.40       3756.4      40    1    1         0         0   
7014           89.20      3645.75      41    1    1         0         0   
7015           85.20      2874.45      34    1    1         0         0   
7016           49.95        49.95       1    0    1         0         0   
7017           20.65      1020.75      51    0    1         0         1   
7018           70.65        70.65       1    1    1         0         0   
7019           20.15          826      39    0    1         0         1   
7020           19.20          239      12    1    1         0         0   
7021           59.80        727.8      12    1    1         1         0   
7022          104.95       7544.3      72    1    1         1         0   
7023          103.50       6479.4      63    1    1         0         0   
7024           84.80      3626.35      44    1    1         0         0   
7025           95.05       1679.4      18    1    1         0         0   
7026           44.20       403.35       9    1    1         0         0   
7027           73.35       931.55      13    0    1         0         0   
7028           64.10      4326.25      68    0    1         0         1   
7029           44.40       263.05       6    1    0         0         0   
7030           20.05        39.25       2    1    1         0         0   
7031           60.00       3316.1      55    0    1         1         0   
7032           75.75        75.75       1    1    1         0         0   
7033           69.50      2625.25      38    1    1         0         0   
7034          102.95      6886.

In [96]:
x=df.iloc[:,[0,2,3,4,5,6,7,8,9]].values
x


array([[ 29.85,   1.  ,   1.  , ...,   0.  ,   1.  ,   0.  ],
       [ 56.95,  34.  ,   0.  , ...,   0.  ,   0.  ,   1.  ],
       [ 53.85,   2.  ,   1.  , ...,   0.  ,   0.  ,   1.  ],
       ...,
       [ 29.6 ,  11.  ,   1.  , ...,   0.  ,   1.  ,   0.  ],
       [ 74.4 ,   4.  ,   1.  , ...,   0.  ,   0.  ,   1.  ],
       [105.65,  66.  ,   1.  , ...,   0.  ,   0.  ,   0.  ]])

In [97]:
x.shape

(7043, 9)

In [98]:
y=df.iloc[:,-1].values
y
y

array([0, 0, 1, ..., 0, 1, 0], dtype=uint8)

In [99]:
from sklearn.model_selection import train_test_split

In [130]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=.20)

In [131]:
from sklearn.linear_model import LogisticRegression

In [132]:
lr=LogisticRegression()

In [133]:
lr.fit(x_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [134]:
# prediction
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=uint8)

In [137]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [129]:

# confusion matrix
confusion_matrix(y_test,y_pred)

array([[1172,  136],
       [ 222,  231]], dtype=int64)

In [138]:
# accuracy
accuracy_score(y_test,y_pred)

0.794889992902768

In [139]:
# precision
precision_score(y_test,y_pred)

0.6503267973856209

In [141]:
# recall
recall_score(y_test,y_pred)

0.5223097112860893

In [142]:
# f1 score
f1_score(y_test,y_pred)

0.5793304221251819