In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline



In [6]:
df=pd.read_csv("Two_points_KNN.csv")
df.head(3)

-2.543456253616113  -10.81635752298698  0
0            9.434466           -2.572000  0
1            3.368646          -10.194671  0
2            1.341407           -4.204140  0

In [4]:
df.keys()

Index(['-2.543456253616113', '-10.81635752298698', '0'], dtype='object')

In [5]:
df["0"].values

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [9]:
x=df.iloc[:,0:2]
y=df.iloc[:,-1]
y.head(2)

0    0
1    0
Name: 0, dtype: int64

In [8]:
x.head(2)

-2.543456253616113  -10.81635752298698
0            9.434466           -2.572000
1            3.368646          -10.194671

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=10)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
k= KNeighborsClassifier()

In [15]:
k.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [17]:
# predictions
y_pred=k.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [22]:
# confusion matrix
confusion_matrix(y_test,y_pred)

array([[215,   0],
       [  0, 185]], dtype=int64)

In [23]:
# accuracy
accuracy_score(y_test,y_pred)

1.0

In [24]:
# precision
precision_score(y_test,y_pred)

1.0

In [28]:
# recall
recall_score(y_test,y_pred)

1.0

In [29]:
# f1 score
f1_score(y_test,y_pred)

1.0