In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
dataset=pd.read_csv("Visitor_Prediction_Multiple_Linear_Regression_data.csv")


In [4]:
dataset.keys()

Index(['Date', 'Views_show', 'Visitors', 'Views_platform', 'Ad_impression',
       'Cricket_match_india', 'Character_A', 'Unnamed: 7'],
      dtype='object')

In [5]:
dataset.head()

Date  Views_show  Visitors  Views_platform  Ad_impression  \
0  3/1/2017      183738   1260228         1706478     1060860448   
1  3/2/2017      193763   1270561         1690727     1031846645   
2  3/3/2017      210479   1248183         1726157     1010867575   
3  3/4/2017      240061   1492913         1855353     1079194579   
4  3/5/2017      446314   1594712         2041418     1357736987   

   Cricket_match_india  Character_A  Unnamed: 7  
0                    0            0         NaN  
1                    0            0         NaN  
2                    0            0         NaN  
3                    1            0         NaN  
4                    0            0         NaN

In [6]:
dataset.shape

(80, 8)

In [7]:
d=dataset.dropna(axis=1,how="all")
d

Date  Views_show  Visitors  Views_platform  Ad_impression  \
0    3/1/2017      183738   1260228         1706478     1060860448   
1    3/2/2017      193763   1270561         1690727     1031846645   
2    3/3/2017      210479   1248183         1726157     1010867575   
3    3/4/2017      240061   1492913         1855353     1079194579   
4    3/5/2017      446314   1594712         2041418     1357736987   
5    3/6/2017      342997   1330689         1742540     1140228426   
6    3/7/2017      227313   1363579         1821742     1113811802   
7    3/8/2017      180313   1353483         1795456     1083475096   
8    3/9/2017      178800   1345428         1794157     1067636147   
9   3/10/2017      201180   1344540         1834967     1081234843   
10  3/11/2017      218956   1500926         1926280     1119900035   
11  3/12/2017      437117   1554859         2015050     1390620085   
12  3/13/2017      263638   1438887         1808967     1231295791   
13  3/14/2017      185896   1459500         1864134     1210330496   
14  3/15/2017      184346   1410668         1896352     1189319112   
15  3/16/2017      132409   1394130         1867785     1152287474   
16  3/17/2017      169225   1438125         1885937     1172698178   
17  3/18/2017      251851   1582773         2016477     1329477115   
18  3/19/2017      476130   1723653         2155393     1714732753   
19  3/20/2017      279880   1528669         1924030     1588375831   
20  3/21/2017      215077   1538487         2015064     1554738251   
21  3/22/2017      173280   1474098         1967000     1439043318   
22  3/23/2017      200993   1484382         1998116     1420880566   
23  3/24/2017      206830   1461298         1965232     1402238110   
24  3/25/2017      236106   1678527         2096071     1469853604   
25  3/26/2017      650563   1924046         2465763     2158026705   
26  3/27/2017      460492   1612675         2165206     1928850028   
27  3/28/2017      379396   1635533         2241286     1830391771   
28  3/29/2017      343223   1568398         2224833     1710096924   
29  3/30/2017      333613   1630580         2134012     1654933815   
..        ...         ...       ...             ...            ...   
50  4/20/2017      169074   1785345         2390240     1346215059   
51  4/21/2017      182208   1810697         2387054     1323744093   
52  4/22/2017      369758   2143350         2704661     1336157323   
53  4/23/2017      712778   2344650         3064422     1890967819   
54  4/24/2017      349008   2060757         2560083     1590193671   
55  4/25/2017      218466   1928796         2441818     1383577770   
56  4/26/2017      208445   1848354         2388369     1294777190   
57  4/27/2017      164043   1772449         2303380     1216537437   
58  4/28/2017      162815   1727098         2189048     1145369229   
59  4/29/2017      266086   1953231         2462984     1200654188   
60  4/30/2017      544814   2187064         2731451     1698345214   
61   5/1/2017      279700   1904704         2323887     1623666951   
62   5/2/2017      196026   1816855         2294150     1388283566   
63   5/3/2017      162150   1780230         2278880     1262254571   
64   5/4/2017      143112   1731468         2214359     1199377174   
65   5/5/2017      140666   1738676         2160395     1189257839   
66   5/6/2017      280065   2016144         2423599     1342773863   
67   5/7/2017      562943   2163629         2681882     1686752144   
68   5/8/2017      271341   1840748         2249542     1403797010   
69   5/9/2017      217791   1821016         2313219     1321700567   
70  5/10/2017      142302   1784534         2256757     1229347176   
71  5/11/2017      110202   1689260         2145511     1146505497   
72  5/12/2017      102520   1697576         2135342     1161183285   
73  5/13/2017      253228   1900320         2340236     1190253439   
74  5/14/2017      631962   2135756         2603553     1614010862   
75  5/15/2017      

In [8]:
d.shape

(80, 7)

In [9]:
d.keys()

Index(['Date', 'Views_show', 'Visitors', 'Views_platform', 'Ad_impression',
       'Cricket_match_india', 'Character_A'],
      dtype='object')

In [10]:
x=d.iloc[:,0:8].drop(["Visitors","Date"],axis=1)
x

Views_show  Views_platform  Ad_impression  Cricket_match_india  \
0       183738         1706478     1060860448                    0   
1       193763         1690727     1031846645                    0   
2       210479         1726157     1010867575                    0   
3       240061         1855353     1079194579                    1   
4       446314         2041418     1357736987                    0   
5       342997         1742540     1140228426                    0   
6       227313         1821742     1113811802                    0   
7       180313         1795456     1083475096                    0   
8       178800         1794157     1067636147                    0   
9       201180         1834967     1081234843                    0   
10      218956         1926280     1119900035                    0   
11      437117         2015050     1390620085                    0   
12      263638         1808967     1231295791                    0   
13      185896         1864134     1210330496                    0   
14      184346         1896352     1189319112                    0   
15      132409         1867785     1152287474                    0   
16      169225         1885937     1172698178                    0   
17      251851         2016477     1329477115                    0   
18      476130         2155393     1714732753                    0   
19      279880         1924030     1588375831                    0   
20      215077         2015064     1554738251                    0   
21      173280         1967000     1439043318                    0   
22      200993         1998116     1420880566                    0   
23      206830         1965232     1402238110                    0   
24      236106         2096071     1469853604                    0   
25      650563         2465763     2158026705                    0   
26      460492         2165206     1928850028                    0   
27      379396         2241286     1830391771                    0   
28      343223         2224833     1710096924                    0   
29      333613         2134012     1654933815                    0   
..         ...             ...            ...                  ...   
50      169074         2390240     1346215059                    0   
51      182208         2387054     1323744093                    0   
52      369758         2704661     1336157323                    0   
53      712778         3064422     1890967819                    0   
54      349008         2560083     1590193671                    0   
55      218466         2441818     1383577770                    0   
56      208445         2388369     1294777190                    0   
57      164043         2303380     1216537437                    0   
58      162815         2189048     1145369229                    0   
59      266086         2462984     1200654188                    0   
60      544814         2731451     1698345214                    0   
61      279700         2323887     1623666951                    0   
62      196026         2294150     1388283566                    0   
63      162150         2278880     1262254571                    0   
64      143112         2214359     1199377174                    0   
65      140666         2160395     1189257839                    0   
66      280065         2423599     1342773863                    0   
67      562943         2681882     1686752144                    0   
68      271341         2249542     1403797010                    0   
69      217791         2313219     1321700567                    0   
70      142302         2256757     1229347176                    0   
71      110202         2145511     1146505497                    0   
72      102520         2135342     1161183285                    0   
73      253228         2340236     1190253439                    1   
74      631962         2603553     1614010862                    1   
75      313945

In [11]:
x.shape

(80, 5)

In [36]:
x.head().values

array([[    183738,    1706478, 1060860448,          0,          0],
       [    193763,    1690727, 1031846645,          0,          0],
       [    210479,    1726157, 1010867575,          0,          0],
       [    240061,    1855353, 1079194579,          1,          0],
       [    446314,    2041418, 1357736987,          0,          0]],
      dtype=int64)

In [21]:
y=d.Visitors.values
y

array([1260228, 1270561, 1248183, 1492913, 1594712, 1330689, 1363579,
       1353483, 1345428, 1344540, 1500926, 1554859, 1438887, 1459500,
       1410668, 1394130, 1438125, 1582773, 1723653, 1528669, 1538487,
       1474098, 1484382, 1461298, 1678527, 1924046, 1612675, 1635533,
       1568398, 1630580, 1588526, 1684842, 1902556, 1668290, 1727040,
       1615949, 1589841, 1568119, 1834463, 1981242, 1689178, 1700031,
       1598403, 1613314, 1697655, 1917386, 2026102, 1811644, 1812134,
       1796219, 1785345, 1810697, 2143350, 2344650, 2060757, 1928796,
       1848354, 1772449, 1727098, 1953231, 2187064, 1904704, 1816855,
       1780230, 1731468, 1738676, 2016144, 2163629, 1840748, 1821016,
       1784534, 1689260, 1697576, 1900320, 2135756, 1808684, 1814227,
       1755803, 1749654, 1746735], dtype=int64)

In [22]:
from sklearn.model_selection import train_test_split

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=12)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
lr=LinearRegression()


In [32]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
# prediction
y_p=lr.predict(x_test)
y_p


array([1876310.97528334, 1395754.49639917, 1473930.3249952 ,
       1382920.12959253, 1674012.26602354, 1723496.87123922,
       1380534.54877569, 2043400.34668621, 1558100.58092719,
       1574134.02485783, 1591028.15850592, 1521225.20702793,
       1898485.64918143, 1557198.93801887, 2271807.09502258,
       1547012.85450427])

In [39]:
from sklearn.metrics import r2_score


In [40]:
r2_score(y_test,y_p)

0.9504285590917474